# Database (from Render env variables)
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# Server
# application-prod.properties
server.address=0.0.0.0
server.port=${PORT:10000}

# Logging (cleaner logs)
logging.level.root=INFO
# Temporary debug — remove after confirming
logging.level.com.zaxxer.hikari=DEBUG

spring.jpa.properties.hibernate.boot.allow_jdbc_metadata_access=false

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect