# Database (from Render env variables)
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# Server
# application-prod.properties
server.address=0.0.0.0
server.port=${PORT:5000}

# Logging (cleaner logs)
logging.level.root=INFO